### ISSUE TITLE
preferences not saved

### ISSUE THREAD

**Issue by muralikodali** [ikipatang/shaarli-web-extension#2]
After restart of firefox, this extension is not working.
preferences saved are lost after restart of firefox.

**Comment by ikipatang** [comment]
Hi @muralikodali , i need more information
Which version of firefox are you using ?
Is it the only settings you are loosing ?

**Comment by muralikodali** [comment]
It's firefox 57 on ubuntu mate 16.04

On 06-Dec-2017 6:08 PM, "ikipatang" <notifications@github.com> wrote:

Hi @muralikodali <https://github.com/muralikodali> , i need more information
Which version of firefox are you using ?
Is it the only settings you are loosing ?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/ikipatang/shaarli-web-extension/issues/2#issuecomment-349627285>,
or mute the thread

**Comment by ikipatang** [comment]
Does it work for in version 0.0.2 ?
https://addons.mozilla.org/fr/firefox/addon/web-extension-for-shaarli/versions/

**Comment by qwertygc** [comment]
I have the same problem in Firefox Quantum in Linux Mint 18.2

**Comment by muralikodali** [comment]
i have tried both 0.2.2 and 0.0.2
same problem ( preferences are not stored and shaarli icon disappearing from main bar ) with 0.2.2.
in case of 0.0.2 there are more problems though preferences are saved. Restarting firefox shows multiple windows in different sizes and to save link we have to drag shaarli dialog box downwards every time.

**Comment by ikipatang** [comment]
I think, it's the other versions that created you the problem on 0.0.2
From a clean profil of firefox, 0.0.2 works but i see your problems begins in version 0.2.2

Time to play the "pick six things that are different" game.

I'm sorry, i don't think i will sort out what is wrong until saturday but i will try to find out before

**Comment by ikipatang** [comment]
Fixed, new version [v0.2.6](https://github.com/ikipatang/shaarli-web-extension/releases/tag/v0.2.6)
Firefox should accept in a few hours

**Comment by muralikodali** [comment]
i have tested v0.2.6 . preferences are saved on reopening firefox. But address bar icon disappearing for some time and again reappearing. some times on reopening, firefox resizing unexpectedly and after unmaximizing and maximizing , firefox window is regaining original size (full window).
i request you to add in context menu -> add link to shaarli (option) as it is very convenient, because we can add link to shaarli without opening link.

**Comment by ikipatang** [comment]
I'm aware about the problem with the addressbar button

Can you explain me how you want to use the context menu button ?
Does it share the link on shaarli without opening the popup ?

**Comment by muralikodali** [comment]
Yes, it is to share the link with shaarli without opening pop up window.
Some pages contain multiple links where we can share some links dirrectly
without opening each and every url.

**Comment by ikipatang** [comment]
Can i close this ticket and start talking on other issues ?
I have create : 
- New suggestion issue #3 for the context menu
- New bug issue #4 for the address bar button
