### ISSUE TITLE
Addressbar button disappear

### ISSUE THREAD

**Issue by ikipatang** [ikipatang/shaarli-web-extension#4]
Bug reported by @muralikodali

Discussion from issue [#2](https://github.com/ikipatang/shaarli-web-extension/issues/2#issuecomment-350207498)
```
address bar icon disappearing for some time and again reappearing. 
some times on reopening, 
firefox resizing unexpectedly and after unmaximizing and maximizing ,
firefox window is regaining original size (full window).
```

**Comment by muralikodali** [comment]
preferences are saved now and there is some good progress in address bar icon appearance and firefox window resizing after recent update
