### ISSUE TITLE
Transfer ownership of original repos & AMO

### ISSUE THREAD

**Issue by aeris** [ikipatang/shaarli-web-extension#5]
Hello !

Thanks for porting this extension to webext, I have no time to do this…
If you want, I can add you as owner of the original AMO extension & github repository, to continue the travel with old users.

Cheers

**Comment by ikipatang** [comment]
Hi, 
First of all, thank you for the first extension and i really apreciate your offer

You think, we should upload the new version under the old name ?

**Comment by aeris** [comment]
Yep, to upgrade old users too, without manual interaction 😄
I just need an email to add you on AMO.

**Comment by ikipatang** [comment]
Do you know a way to send private message ?

**Comment by ikipatang** [comment]
Hi Aeris,

Can we communicate with this address ?

Le 17/12/2017 à 02:02, aeris a écrit :

Yep, to upgrade old users too, without manual interaction 😄
I just need an email to add you on AMO.

**Comment by aeris** [comment]
You have my contact here : https://imirhil.fr/#contact
